feat: added crud for curriculum
SmashGrade/backend pull request #42
Opened 2024-03-05 19:05 UTC by FerberJ

added CRUD for Curriculum.

2024-03-05 22:25 UTC, stafel requested changes
code looks good but needs a testcase at least on dao level to ensure functionality

2024-03-06 20:16 UTC, FerberJ commented
added curriculumdao test.

2024-03-07 18:36 UTC, stafel approved these changes

2024-03-07 18:37 UTC, stafel commented
looks good, tests work

2024-03-08 18:30 UTC, merged